services:
  backend:
    ports: !reset []
    environment:
      - VIRTUAL_HOST=backend.info.localhost
      - VIRTUAL_PORT=80
      - NODE_PORT=80
    depends_on:
      - proxy

  frontend:
    ports: !reset []
    environment:
      - VIRTUAL_HOST=info.localhost
      - VIRTUAL_PORT=80
    depends_on:
      - proxy
