include:
  - projects/backend/docker-compose.yml
  - projects/frontend/docker-compose.yml

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
